#!/bin/bash
touch jessicaOrtega.txt
mkdir -p /var/public/sales/data 
mkdir /var/public/sales/projects
mkdir -p /var/public/techs/data 
mkdir /var/public/techs/projects
mkdir -p /var/public/devops/data 
mkdir /var/public/devops/projects
groupadd sales
groupadd techs
groupadd devops
chgrp -R sales /var/public/sales
chgrp -R techs /var/public/techs
chgrp -R devops /var/public/devops 
chmod -R 2770 /var/public/sales
chmod -R 2770 /var/public/techs
chmod -R 2770 /var/public/devops 
cp -R /etc/skel /etc/skel-sales
cp -R /etc/skel /etc/skel-techs
cp -R /etc/skel /etc/skel-devops
#vi /etc/skel-sales/.bashrc
#vi /etc/skel-techs/.bash_profile
mkdir /home/SALES
mkdir /home/TECHS
mkdir /home/DEVOPS
groupadd looneytunes
useradd -c "Bugs Bunny" -g sales -G looneytunes -k /etc/skel-sales -m -d /home/SALES/bbunny bbunny
echo Pa11word | passswd --stin bbunny
useradd -c "Tasmanian Devil" -g sales -G looneytunes -k /etc/skel-sales -m -d /home/SALES/tdevil tdevil
echo Pa11word | passswd --stin tdevil
useradd -c "Marvin the Martian" -g sales -G looneytunes -k /etc/skel-sales -m -d /home/SALES/mmartian mmartian
echo Pa11word | passswd --stin mmartian
useradd -c "Sylvester" -g sales -G looneytunes -k /etc/skel-sales -m -d /home/SALES/sylvester sylvester
echo Pa11word | passswd --stin sylvester
useradd -c "Yosemite Sam" -g techs -G looneytunes -k /etc/skel-techs -m -d /home/TECHS/ysam ysam
echo Pa11word | passswd --stin ysam
useradd -c "Speedy Gonzales" -g techs -G looneytunes -k /etc/skel-techs -m -d /home/TECHS/sgonzales sgonzales
echo Pa11word | passswd --stin sgonzales
useradd -c "Pepe Le Pew" -g techs -G looneytunes -k /etc/skel-techs -m -d /home/TECHS/ppew ppew
echo Pa11word | passswd --stin ppew
useradd -c "Wile E. Coyote" -g techs -G looneytunes -k /etc/skel-techs -m -d /home/TECHS/wcoyote wcoyote
echo Pa11word | passswd --stin wcoyote
useradd -c "Foghorn Leghorn" -g devops -G looneytunes -k /etc/skel-devops -m -d /home/DEVOPS/fleghorn fleghorn
echo Pa11word | passswd --stin fleghorn
useradd -c "Elmer Fudd" -g devops -G looneytunes -k /etc/skel-devops -m -d /home/DEVOPS/efudd efudd
echo Pa11word | passswd --stin efudd
useradd -c "Tweety" -g devops -G looneytunes -k /etc/skel-devops -m -d /home/DEVOPS/tweety tweety
echo Pa11word | passswd --stin tweety
useradd -c "Porky Pig" -g devops -G looneytunes -k /etc/skel-devops -m -d /home/DEVOPS/ppig ppig
echo Pa11word | passswd --stin ppig


